Support location message type
Nheko-Reborn/mtxclient pull request #88
Opened 2023-01-06 19:25 UTC by hamzehnasajpour

https://github.com/Nheko-Reborn/mtxclient/issues/87

2023-01-08 00:46 UTC, deepbluev7 requested changes
Looks good in general, but I found some small nits. Thank you for working on this!

2023-01-08 00:46 UTC, deepbluev7 commented on lib/structs/events/common.cpp
> +        info.blurhash = obj.at("xyz.amorgan.blurhash").get<std::string>();
I think this is wrong. I think only the thumbnail has a blurhash.

2023-01-08 00:46 UTC, deepbluev7 commented on lib/structs/events/common.cpp
> +        obj["thumbnail_info"] = info.thumbnail_info;
I think this should be serialized when a thumbnail_url or a thumbnail_file is present.

2023-01-08 00:46 UTC, deepbluev7 commented on lib/structs/events/common.cpp
> +        obj["xyz.amorgan.blurhash"] = info.blurhash;
(Also not existing, afaik)

2023-01-08 00:46 UTC, deepbluev7 commented on lib/structs/events/collections.cpp
> +                // container.emplace_back(location);
I think you can delete these.

2023-01-08 00:46 UTC, deepbluev7 commented on lib/structs/responses/common.cpp
> +                    container.emplace_back(location);
Can you write that in the style of the lines above, i.e.:

```suggestion
                    container.emplace_back(events::RoomEvent<events::msg::Location>(e));
```

2023-07-22 20:58 UTC, LorenDB commented
@hamzehnasajpour: ping! Are you still planning to finish this? :)

2023-08-22 13:52 UTC, hamzehnasajpour commented
> @hamzehnasajpour: ping! Are you still planning to finish this? :)

Unfortunately I was so busy and couldn't update and finish it. Is it possible to fix it by you or someone else?

2023-08-22 18:30 UTC, LorenDB commented
Somebody should be able to pick it up. Thank you for providing the initial implementation!

2025-03-22 20:45 UTC, deepbluev7 commented
Picked up in #111, thanks for the initial code!

2025-03-22 20:45 UTC, closed without merging